### ISSUE TITLE
合成画像を本番環境に表示する

### ISSUE THREAD

**Issue by masaya7** [masaya7/museum_app#56]
### 質問内容・実現したいこと
本番環境でユーザーが投稿した画像とs3に保存している額縁の画像をminimagickで合成して投稿できるようにしたい。

### 現状発生している問題・エラーメッセージ
本番環境で額縁を合成して新規投稿すると以下のようなエラー発生します。
```
2023-09-05T09:24:30Z app[17811616a41618] nrt [info]I, [2023-09-05T09:24:30.077038 #255]  INFO -- : [03f2de85-4403-45e5-bae5-07b13374df5f]   Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"image"=>#<ActionDispatch::Http::UploadedFile:0x00007fc3954f69f0 @tempfile=#<Tempfile:/tmp/RackMultipart20230905-255-v4bwig.png>, @content_type="image/png", @original_filename="sample.png", @headers="Content-Disposition: form-data; name=\"post[image]\"; filename=\"sample.png\"\r\nContent-Type: image/png\r\n">, "title"=>"sample", "body"=>"sample", "status"=>"published"}, "commit"=>"OK"}
2023-09-05T09:24:30Z app[17811616a41618] nrt [info]I, [2023-09-05T09:24:30.271116 #255]  INFO -- : [03f2de85-4403-45e5-bae5-07b13374df5f] Completed 500 Internal Server Error in 194ms (ActiveRecord: 1.4ms | Allocations: 3300)
2023-09-05T09:24:30Z app[17811616a41618] nrt [info]F, [2023-09-05T09:24:30.271857 #255] FATAL -- : [03f2de85-4403-45e5-bae5-07b13374df5f]
2023-09-05T09:24:30Z app[17811616a41618] nrt [info][03f2de85-4403-45e5-bae5-07b13374df5f] Errno::ENOENT (No such file or directory @ rb_sysopen - uploads/tmp/1693905870-746540478756659-0002-6026/sample.png):
```

### 動いている処理
本番環境で画像合成なしの投稿（add_frameメソッドをコメントアウトした状態）は成功できています。その際画像はs3の`uploads/post/image/数字/画像データ`に保存されます。
開発環境で画像合成あり・なし共に投稿成功できています。

### 該当のソースコード
- post.rb
```
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  before_save :add_frame
  has_one_attached :image
  validates :image, presence: true

  private

  def add_frame
    return unless image.present?

    input_path = image.path
    frame_path = Rails.configuration.frame_image_path
    image = MiniMagick::Image.open(input_path)
    image.resize "210x280!"
    frame = MiniMagick::Image.open(frame_path)
    frame.resize "210x280!"
    result = image.composite(frame) do |c|
      c.compose "Over"
    end
    output_filename = "#{Time.now.to_i}.png"
    output_path = Rails.root.join("public", "uploads", "post", "image", output_filename)
    result.write(output_path)
    self.compose_image = "/uploads/post/image/#{output_filename}"
  end
end
```

- pruduction.rb
```
  config.frame_image_path = 'https://museum1-app.s3.ap-northeast-1.amazonaws.com/uploads/%E9%A1%8D%E7%B8%81.png'
```

### エラーから考えられる原因

1,`Errno::ENOENT (No such file or directory @ rb_sysopen`とあることからファイルやディレクトリがない。
2,新規投稿時`compose_image`カラムがない。
3,`Completed 500 Internal Server Error`が出ている
### 試したこと
1,私の想定では、postモデルのadd_frameメソッドにある、"/uploads/post/image/#{output_filename}"に保存したいと考えています。しかし実際は`uploads/tmp/~`に保存されています。tmp以下に保存する設定は記述していないので、原因追求しています。
2,postモデルにはcompose_imageが存在している。
開発環境で新規投稿すると`["compose_image", "/uploads/post/image/1693906839.png"]`と画像データが入っているので、パラメータの付与は正しくできている。本番環境でもデータが入るように工夫すべきだが、手段がわからない。
3,サーバーに関するエラー。投稿に関するパラメーターはwebサーバーに送れているようなので、画像合成し表示する間でエラーが発生している？

現状を整理すると、
開発環境 add_frameなし:新規投稿成功
開発環境 add_frameあり:新規投稿成功
本番環境 add_frameなし:新規投稿成功
本番環境 add_frameあり:新規投稿失敗
となることから、s3に保存した`額縁.png`に関するエラー（合成できないなど）が原因かと考えています。

以上となっております。
ご教示いただけますと幸いです。

**Comment by masaya7** [comment]
```
# 開発環境で新規投稿(額縁あり)
Started POST "/posts" for ::1 at 2023-09-07 15:15:06 +0900
Processing by PostsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"image"=>#<ActionDispatch::Http::UploadedFile:0x000000011a25f240 @tempfile=#<Tempfile:/var/folders/jm/2s2t39653ws9p0n_nygtfw8h0000gn/T/RackMultipart20230907-58531-bh0flo.png>, @content_type="image/png", @original_filename="sample.png", @headers="Content-Disposition: form-data; name=\"post[image]\"; filename=\"sample.png\"\r\nContent-Type: image/png\r\n">, "title"=>"sample", "body"=>"sample", "status"=>"published"}, "commit"=>"OK"}
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/helpers/sessions_helper.rb:15:in `current_user'
DEPRECATION WARNING: #extension_whitelist is deprecated, use #extension_allowlist instead. (called from create at /Users/usuimasaya/workspace/runteq/museum_app/app/controllers/posts_controller.rb:15)
  CACHE User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  TRANSACTION (0.2ms)  begin transaction
  ↳ app/controllers/posts_controller.rb:16:in `create'
  Post Create (0.9ms)  INSERT INTO "posts" ("image", "body", "user_id", "created_at", "updated_at", "status", "title", "compose_image") VALUES (?, ?, ?, ?, ?, ?, ?, ?)  [["image", "sample.png"], ["body", "sample"], ["user_id", 1], ["created_at", "2023-09-07 06:15:06.567052"], ["updated_at", "2023-09-07 06:15:06.567052"], ["status", 0], ["title", "sample"], ["compose_image", "/uploads/post/image/1694067306.png"]]
  ↳ app/controllers/posts_controller.rb:16:in `create'
  TRANSACTION (1.2ms)  commit transaction
  ↳ app/controllers/posts_controller.rb:16:in `create'
Redirected to http://localhost:3000/index
Completed 302 Found in 327ms (ActiveRecord: 2.6ms | Allocations: 10110)
```
```
# 本番環境で新規投稿(額縁なし)
2023-09-07T06:27:40Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:40.562691 #255]  INFO -- : [e9ad64d2-f2f7-4ac2-ae48-e1661d394f8b] Started POST "/posts" for 2a09:8280:1::4e:6adf at 2023-09-07 06:27:40 +0000
2023-09-07T06:27:40Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:40.563685 #255]  INFO -- : [e9ad64d2-f2f7-4ac2-ae48-e1661d394f8b] Processing by PostsController#create as HTML
2023-09-07T06:27:40Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:40.563807 #255]  INFO -- : [e9ad64d2-f2f7-4ac2-ae48-e1661d394f8b]   Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"image"=>#<ActionDispatch::Http::UploadedFile:0x00007f20144e0378 @tempfile=#<Tempfile:/tmp/RackMultipart20230907-255-u2vr49.png>, @content_type="image/png", @original_filename="sample.png", @headers="Content-Disposition: form-data; name=\"post[image]\"; filename=\"sample.png\"\r\nContent-Type: image/png\r\n">, "title"=>"sample", "body"=>"sample", "status"=>"published"}, "commit"=>"OK"}
2023-09-07T06:27:41Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:41.372348 #255]  INFO -- : [e9ad64d2-f2f7-4ac2-ae48-e1661d394f8b] Redirected to https://msyapp1.fly.dev/index
2023-09-07T06:27:41Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:41.372616 #255]  INFO -- : [e9ad64d2-f2f7-4ac2-ae48-e1661d394f8b] Completed 302 Found in 809ms (ActiveRecord: 7.2ms | Allocations: 12996)
2023-09-07T06:27:41Z app[17811616a41618] nrt [info]ERROR No such file or directory (os error 2)
2023-09-07T06:27:41Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:41.403195 #255]  INFO -- : [2a754e56-9659-4fcd-8f76-ef6e2a42dd07] Started GET "/index" for 2a09:8280:1::4e:6adf at 2023-09-07 06:27:41 +0000
2023-09-07T06:27:41Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:41.404150 #255]  INFO -- : [2a754e56-9659-4fcd-8f76-ef6e2a42dd07] Processing by PostsController#index as HTML
2023-09-07T06:27:41Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:41.431497 #255]  INFO -- : [2a754e56-9659-4fcd-8f76-ef6e2a42dd07]   Rendered posts/index.html.erb within layouts/application (Duration: 24.6ms | Allocations: 4698)
2023-09-07T06:27:41Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:41.432918 #255]  INFO -- : [2a754e56-9659-4fcd-8f76-ef6e2a42dd07]   Rendered layout layouts/application.html.erb (Duration: 26.1ms | Allocations: 5691)
2023-09-07T06:27:41Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:41.433248 #255]  INFO -- : [2a754e56-9659-4fcd-8f76-ef6e2a42dd07] Completed 200 OK in 29ms (Views: 14.0ms | ActiveRecord: 12.6ms | Allocations: 6061)
2023-09-07T06:27:41Z app[17811616a41618] nrt [info]I, [2023-09-07T06:27:41.709797 #255]  INFO -- : [574370e4-04d7-45d8-8ac8-8e5e6272f2e8] Started GET "/assets/controllers" for 2a09:8280:1::4e:6adf at 2023-09-07 06:27:41 +0000
2023-09-07T06:27:41Z app[17811616a41618] nrt [info]F, [2023-09-07T06:27:41.710377 #255] FATAL -- : [574370e4-04d7-45d8-8ac8-8e5e6272f2e8]
2023-09-07T06:27:41Z app[17811616a41618] nrt [info][574370e4-04d7-45d8-8ac8-8e5e6272f2e8] ActionController::RoutingError (No route matches [GET] "/assets/controllers"):
2023-09-07T06:27:41Z app[17811616a41618] nrt [info][574370e4-04d7-45d8-8ac8-8e5e6272f2e8]

```
```
# 本番環境で新規投稿(額縁あり)エラー
2023-09-07T06:37:37Z app[17811616a41618] nrt [info]I, [2023-09-07T06:37:37.745911 #255]  INFO -- : [9034a59a-3038-451e-a854-b2f175707879] Started POST "/posts" for 2a09:8280:1::4e:6adf at 2023-09-07 06:37:37 +0000
2023-09-07T06:37:37Z app[17811616a41618] nrt [info]I, [2023-09-07T06:37:37.746883 #255]  INFO -- : [9034a59a-3038-451e-a854-b2f175707879] Processing by PostsController#create as HTML
2023-09-07T06:37:37Z app[17811616a41618] nrt [info]I, [2023-09-07T06:37:37.747019 #255]  INFO -- : [9034a59a-3038-451e-a854-b2f175707879]   Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"image"=>#<ActionDispatch::Http::UploadedFile:0x00007fac285cff18 @tempfile=#<Tempfile:/tmp/RackMultipart20230907-255-3ila23.png>, @content_type="image/png", @original_filename="sample.png", @headers="Content-Disposition: form-data; name=\"post[image]\"; filename=\"sample.png\"\r\nContent-Type: image/png\r\n">, "title"=>"sample", "body"=>"sample", "status"=>"published"}, "commit"=>"OK"}
2023-09-07T06:37:38Z app[17811616a41618] nrt [info]I, [2023-09-07T06:37:38.002670 #255]  INFO -- : [9034a59a-3038-451e-a854-b2f175707879] Completed 500 Internal Server Error in 256ms (ActiveRecord: 1.4ms | Allocations: 7825)
2023-09-07T06:37:38Z app[17811616a41618] nrt [info]F, [2023-09-07T06:37:38.003372 #255] FATAL -- : [9034a59a-3038-451e-a854-b2f175707879]
2023-09-07T06:37:38Z app[17811616a41618] nrt [info][9034a59a-3038-451e-a854-b2f175707879] Errno::ENOENT (No such file or directory @ rb_sysopen - uploads/tmp/1694068657-956823933951829-0001-4523/sample.png):
2023-09-07T06:37:38Z app[17811616a41618] nrt [info][9034a59a-3038-451e-a854-b2f175707879]
2023-09-07T06:37:38Z app[17811616a41618] nrt [info][9034a59a-3038-451e-a854-b2f175707879] app/models/post.rb:29:in `add_frame'
2023-09-07T06:37:38Z app[17811616a41618] nrt [info][9034a59a-3038-451e-a854-b2f175707879] app/controllers/posts_controller.rb:16:in `create'
```

**Comment by masaya7** [comment]
s3のuploads/tmpを削除し、額縁.pngのみがある状態にする。
その後改めて新規投稿すると同様のエラーが発生する
tmpフォルダは、「一時的なフォルダ」なので権限がなくどうしようもないからtmpフォルダに保存された可能性がある？
```
2023-09-07T09:00:46Z app[17811616a41618] nrt [info][94c05448-3471-4014-b92e-6c929b897054] Errno::ENOENT (No such file or directory @ rb_sysopen - uploads/tmp/1694077245-795230185723148-0001-5957/sample.png):
```
s3のuploads以下にpost/image/を作成してみる→変わらず
